version: "3"

services: 
  dbus:
    build: ./dbus
    container_name: dbus
    networks:
      srvbr:
        ipv4_address: 10.121.0.10

  avahi:
    build: ./avahi
    container_name: avahi
    ports:
      - 5353:5353/udp
    network_mode: "host"
    depends_on:
      - dbus

  homebridge-milight:
    build: ./Homebridge_Milight
    container_name: milight
    ports:
      - "51827:51827"
    volumes:
      - ./Homebridge_Milight:/root/.homebridge
    restart: "always"
    networks:
      srvbr:
        ipv4_address: 10.121.0.11
    depends_on:
      - avahi

  homebridge-ikea:
    build: ./Homebridge_Ikea
    container_name: ikea
    ports:
      - "51826:51826"
    volumes:
      - ./Homebridge_Ikea:/root/.homebridge
    restart: "always"
    networks:
      srvbr:
        ipv4_address: 10.121.0.12
    depends_on:
      - avahi

  db:
    # https://hub.docker.com/_/mysql/
    image: mariadb
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql
    networks:
      srvbr:
        ipv4_address: 10.121.0.13

  phpmyadmin:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8001:80
    networks:
      srvbr:
        ipv4_address: 10.121.0.14
    depends_on:
      - db

  owncloud:
    # https://hub.docker.com/_/owncloud/
    image: owncloud
    container_name: owncloud
    ports:
      - 8002:80
    networks:
      srvbr:
        ipv4_address: 10.121.0.15
    depends_on:
      - db
    volumes:
      - ./owncloud/apps:/var/www/html/apps 
      - ./owncloud/config:/var/www/html/config
      - ./owncloud/data:/var/www/html/data

  openldap:
    image: osixia/openldap:1.1.9
    container_name: openldap
    volumes:
      - ./openldap/database:/var/lib/ldap
      - ./openldap/slap.d:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    networks:
     srvbr:
       ipv4_address: 10.121.0.16
  
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: '10.121.0.16'
    ports:
      - 8003:443
    depends_on:
      - openldap
    networks:
     srvbr:
       ipv4_address: 10.121.0.17

  ldap-template:
    build: ./ldap-template
    image: local/ldap-template
    networks:
     srvbr:
      ipv4_address: 10.121.0.18

  shell:
    build: ./shell
    container_name: "shell"
    ports:
      - "2222:2222"
    networks:
      srvbr:
        ipv4_address: 10.121.0.19
    volumes:
      - ./shell/home:/home
        #      - ./shell/ssh:/etc/ssh
    depends_on:
      - ldap-template
    
  afp:
    build: "./afp"
    container_name: "afp"
    ports:
      - 548:548
    volumes:
      - ./afp/afp.conf:/usr/local/etc/afp.conf
    networks:
      srvbr:
        ipv4_address: 10.121.0.20
    depends_on:
      - ldap-template

networks:
  srvbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.121.0.0/16


