version: "3"

services: 
  dbus:
    build: ./dbus
    networks:
      srvbr:
        ipv4_address: 10.121.0.10

  avahi:
    build: ./avahi
    ports:
      - 5353:5353/udp
    network_mode: "host"
    depends_on:
      - dbus

  homebridge-milight:
    build: ./Homebridge_Milight
    ports:
      - "51827:51827"
    volumes:
      - ./Homebridge_Milight:/root/.homebridge
    restart: "always"
    networks:
      srvbr:
        ipv4_address: 10.121.0.11
    depends_on:
      - avahi

  homebridge-ikea:
    build: ./Homebridge_Ikea
    ports:
      - "51826:51826"
    volumes:
      - ./Homebridge_Ikea:/root/.homebridge
    restart: "always"
    networks:
      srvbr:
        ipv4_address: 10.121.0.12
    depends_on:
      - avahi

  db:
    # https://hub.docker.com/_/mysql/
    image: mariadb
    networks:
      srvbr:
        ipv4_address: 10.121.0.13

  # owncloud:
  #   # https://hub.docker.com/_/owncloud/
  #   image: owncloud
  #   ports:
  #     - 8001:80
  #   networks:
  #     srvbr:
  #       ipv4_address: 10.121.0.14
  #   volumes:
  #     - ./owncloud/apps:/var/www/html/apps 
  #     - ./owncloud/config:/var/www/html/config
  #     - ./owncloud/data:/var/www/html/data

networks:
  srvbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.121.0.0/16


